version: "3.8"

services:
  billy-nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2345:80"
    restart: unless-stopped
    volumes:
      - ./app:/var/www/html

  database:
    image: mariadb
    restart: always
    volumes:
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    environment:
      MYSQL_DATABASE: data
      MYSQL_ROOT_PASSWORD: password

  adminer:
    image: adminer
    restart: always
    ports:
      - "1333:8080"

volumes:
  data: